# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Bioindicators
author: team@

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/hammerdirt-analyst/qualite-deau # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

sphinx:
  config:
    html_show_copyright: false
    language: en
    html_theme_options:
      use_download_button: false
      repository_url: https://github.com/hammerdirt-analyst/qualite-deau
      use_issues_button: true
      use_repository_button: true
      extra_footer: |
        <p>
           hammerdirt-hackuarium 2023
        </p>





